# Generated by Django 4.2.3 on 2023-09-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('name_book', models.CharField(max_length=25)),
                ('rating', models.IntegerField()),
                ('review', models.TextField()),
            ],
        ),
    ]
